package com.autobots.automanager.enumeracoes;

public enum PermissaoEnum {
    ADMIN_CRUD, GERENTE_CRUD_USUARIO, GERENTE_CRUD_SERVICO,
    VENDEDOR_CRUD_CLIENTE, VENDEDOR_READ_SERVICO, VENDEDOR_READ_MERCADORIA,
    VENDEDOR_CREATE_VENDA, VENDEDOR_READ_VENDA, CLIENTE_READ_PROPRIO,
    CLIENTE_READ_VENDA;
}